export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
