// Order socket
export const RECEIVE_REFRESH_ORDERS = 'REFRESH-ORDERS-'
export const RECEIVE_ALL_ORDERS = 'ALL_ORDERS'

export const EMIT_FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS'
export const EMIT_ORDER_SERVICED = 'MARK_ORDER_SERVICED'


// Service call socket
export const RECEIVE_SERVICE_CALLED = 'SERVICE_CALLED'
export const RECEIVE_ALL_SERVICE_CALLS = 'ALL_SERVICE_CALLS'

export const EMIT_FETCH_SERVICE_CALLS = 'FETCH_ALL_SERVICE_CALLS'
export const EMIT_SERVICE_CALL_SERVICED = 'SERVICE_CALL_SERVICED'
